spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Raduga14
    driver-class-name: org.postgresql.Driver
  #Show sql logs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
server:
  port: 8080
  servlet:
    context-path: /salon

